//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace EntityData
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class cos_OtherEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new cos_OtherEntities object using the connection string found in the 'cos_OtherEntities' section of the application configuration file.
        /// </summary>
        public cos_OtherEntities() : base("name=cos_OtherEntities", "cos_OtherEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cos_OtherEntities object.
        /// </summary>
        public cos_OtherEntities(string connectionString) : base(connectionString, "cos_OtherEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new cos_OtherEntities object.
        /// </summary>
        public cos_OtherEntities(EntityConnection connection) : base(connection, "cos_OtherEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tbl_Brand> Tbl_Brands
        {
            get
            {
                if ((_Tbl_Brands == null))
                {
                    _Tbl_Brands = base.CreateObjectSet<Tbl_Brand>("Tbl_Brands");
                }
                return _Tbl_Brands;
            }
        }
        private ObjectSet<Tbl_Brand> _Tbl_Brands;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tbl_Item> Tbl_Items
        {
            get
            {
                if ((_Tbl_Items == null))
                {
                    _Tbl_Items = base.CreateObjectSet<Tbl_Item>("Tbl_Items");
                }
                return _Tbl_Items;
            }
        }
        private ObjectSet<Tbl_Item> _Tbl_Items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tbl_ItemsDetail> Tbl_ItemsDetails
        {
            get
            {
                if ((_Tbl_ItemsDetails == null))
                {
                    _Tbl_ItemsDetails = base.CreateObjectSet<Tbl_ItemsDetail>("Tbl_ItemsDetails");
                }
                return _Tbl_ItemsDetails;
            }
        }
        private ObjectSet<Tbl_ItemsDetail> _Tbl_ItemsDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tbl_ItemsDetails_More> Tbl_ItemsDetails_Mores
        {
            get
            {
                if ((_Tbl_ItemsDetails_Mores == null))
                {
                    _Tbl_ItemsDetails_Mores = base.CreateObjectSet<Tbl_ItemsDetails_More>("Tbl_ItemsDetails_Mores");
                }
                return _Tbl_ItemsDetails_Mores;
            }
        }
        private ObjectSet<Tbl_ItemsDetails_More> _Tbl_ItemsDetails_Mores;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tbl_Brands EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTbl_Brands(Tbl_Brand tbl_Brand)
        {
            base.AddObject("Tbl_Brands", tbl_Brand);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tbl_Items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTbl_Items(Tbl_Item tbl_Item)
        {
            base.AddObject("Tbl_Items", tbl_Item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tbl_ItemsDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTbl_ItemsDetails(Tbl_ItemsDetail tbl_ItemsDetail)
        {
            base.AddObject("Tbl_ItemsDetails", tbl_ItemsDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tbl_ItemsDetails_Mores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTbl_ItemsDetails_Mores(Tbl_ItemsDetails_More tbl_ItemsDetails_More)
        {
            base.AddObject("Tbl_ItemsDetails_Mores", tbl_ItemsDetails_More);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cos_Model", Name="Tbl_Brand")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tbl_Brand : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tbl_Brand object.
        /// </summary>
        /// <param name="brandID">Initial value of the BrandID property.</param>
        public static Tbl_Brand CreateTbl_Brand(global::System.Int32 brandID)
        {
            Tbl_Brand tbl_Brand = new Tbl_Brand();
            tbl_Brand.BrandID = brandID;
            return tbl_Brand;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BrandID
        {
            get
            {
                return _BrandID;
            }
            set
            {
                if (_BrandID != value)
                {
                    OnBrandIDChanging(value);
                    ReportPropertyChanging("BrandID");
                    _BrandID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BrandID");
                    OnBrandIDChanged();
                }
            }
        }
        private global::System.Int32 _BrandID;
        partial void OnBrandIDChanging(global::System.Int32 value);
        partial void OnBrandIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BrandName
        {
            get
            {
                return _BrandName;
            }
            set
            {
                OnBrandNameChanging(value);
                ReportPropertyChanging("BrandName");
                _BrandName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BrandName");
                OnBrandNameChanged();
            }
        }
        private global::System.String _BrandName;
        partial void OnBrandNameChanging(global::System.String value);
        partial void OnBrandNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                OnCategoryIDChanging(value);
                ReportPropertyChanging("CategoryID");
                _CategoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryID");
                OnCategoryIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CategoryID;
        partial void OnCategoryIDChanging(Nullable<global::System.Int32> value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ISRun
        {
            get
            {
                return _ISRun;
            }
            set
            {
                OnISRunChanging(value);
                ReportPropertyChanging("ISRun");
                _ISRun = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ISRun");
                OnISRunChanged();
            }
        }
        private Nullable<global::System.Boolean> _ISRun;
        partial void OnISRunChanging(Nullable<global::System.Boolean> value);
        partial void OnISRunChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MinPrice
        {
            get
            {
                return _MinPrice;
            }
            set
            {
                OnMinPriceChanging(value);
                ReportPropertyChanging("MinPrice");
                _MinPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinPrice");
                OnMinPriceChanged();
            }
        }
        private Nullable<global::System.Int32> _MinPrice;
        partial void OnMinPriceChanging(Nullable<global::System.Int32> value);
        partial void OnMinPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxPrice
        {
            get
            {
                return _MaxPrice;
            }
            set
            {
                OnMaxPriceChanging(value);
                ReportPropertyChanging("MaxPrice");
                _MaxPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxPrice");
                OnMaxPriceChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxPrice;
        partial void OnMaxPriceChanging(Nullable<global::System.Int32> value);
        partial void OnMaxPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RangePrice
        {
            get
            {
                return _RangePrice;
            }
            set
            {
                OnRangePriceChanging(value);
                ReportPropertyChanging("RangePrice");
                _RangePrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RangePrice");
                OnRangePriceChanged();
            }
        }
        private Nullable<global::System.Int32> _RangePrice;
        partial void OnRangePriceChanging(Nullable<global::System.Int32> value);
        partial void OnRangePriceChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cos_Model", Name="Tbl_Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tbl_Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tbl_Item object.
        /// </summary>
        /// <param name="itemID">Initial value of the ItemID property.</param>
        public static Tbl_Item CreateTbl_Item(global::System.Int32 itemID)
        {
            Tbl_Item tbl_Item = new Tbl_Item();
            tbl_Item.ItemID = itemID;
            return tbl_Item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemID
        {
            get
            {
                return _ItemID;
            }
            set
            {
                if (_ItemID != value)
                {
                    OnItemIDChanging(value);
                    ReportPropertyChanging("ItemID");
                    _ItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemID");
                    OnItemIDChanged();
                }
            }
        }
        private global::System.Int32 _ItemID;
        partial void OnItemIDChanging(global::System.Int32 value);
        partial void OnItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItenName
        {
            get
            {
                return _ItenName;
            }
            set
            {
                OnItenNameChanging(value);
                ReportPropertyChanging("ItenName");
                _ItenName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItenName");
                OnItenNameChanged();
            }
        }
        private global::System.String _ItenName;
        partial void OnItenNameChanging(global::System.String value);
        partial void OnItenNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ItemBrand
        {
            get
            {
                return _ItemBrand;
            }
            set
            {
                OnItemBrandChanging(value);
                ReportPropertyChanging("ItemBrand");
                _ItemBrand = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ItemBrand");
                OnItemBrandChanged();
            }
        }
        private global::System.String _ItemBrand;
        partial void OnItemBrandChanging(global::System.String value);
        partial void OnItemBrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CategoryID_N
        {
            get
            {
                return _CategoryID_N;
            }
            set
            {
                OnCategoryID_NChanging(value);
                ReportPropertyChanging("CategoryID_N");
                _CategoryID_N = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryID_N");
                OnCategoryID_NChanged();
            }
        }
        private Nullable<global::System.Int32> _CategoryID_N;
        partial void OnCategoryID_NChanging(Nullable<global::System.Int32> value);
        partial void OnCategoryID_NChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CategoryName_V
        {
            get
            {
                return _CategoryName_V;
            }
            set
            {
                OnCategoryName_VChanging(value);
                ReportPropertyChanging("CategoryName_V");
                _CategoryName_V = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CategoryName_V");
                OnCategoryName_VChanged();
            }
        }
        private global::System.String _CategoryName_V;
        partial void OnCategoryName_VChanging(global::System.String value);
        partial void OnCategoryName_VChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String merchantname
        {
            get
            {
                return _merchantname;
            }
            set
            {
                OnmerchantnameChanging(value);
                ReportPropertyChanging("merchantname");
                _merchantname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("merchantname");
                OnmerchantnameChanged();
            }
        }
        private global::System.String _merchantname;
        partial void OnmerchantnameChanging(global::System.String value);
        partial void OnmerchantnameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cos_Model", Name="Tbl_ItemsDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tbl_ItemsDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tbl_ItemsDetail object.
        /// </summary>
        /// <param name="productID">Initial value of the ProductID property.</param>
        public static Tbl_ItemsDetail CreateTbl_ItemsDetail(global::System.Int64 productID)
        {
            Tbl_ItemsDetail tbl_ItemsDetail = new Tbl_ItemsDetail();
            tbl_ItemsDetail.ProductID = productID;
            return tbl_ItemsDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int64 _ProductID;
        partial void OnProductIDChanging(global::System.Int64 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Flipkart
        {
            get
            {
                return _Flipkart;
            }
            set
            {
                OnFlipkartChanging(value);
                ReportPropertyChanging("Flipkart");
                _Flipkart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Flipkart");
                OnFlipkartChanged();
            }
        }
        private Nullable<global::System.Double> _Flipkart;
        partial void OnFlipkartChanging(Nullable<global::System.Double> value);
        partial void OnFlipkartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Paytm
        {
            get
            {
                return _Paytm;
            }
            set
            {
                OnPaytmChanging(value);
                ReportPropertyChanging("Paytm");
                _Paytm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Paytm");
                OnPaytmChanged();
            }
        }
        private Nullable<global::System.Double> _Paytm;
        partial void OnPaytmChanging(Nullable<global::System.Double> value);
        partial void OnPaytmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> SnapDeal
        {
            get
            {
                return _SnapDeal;
            }
            set
            {
                OnSnapDealChanging(value);
                ReportPropertyChanging("SnapDeal");
                _SnapDeal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SnapDeal");
                OnSnapDealChanged();
            }
        }
        private Nullable<global::System.Double> _SnapDeal;
        partial void OnSnapDealChanging(Nullable<global::System.Double> value);
        partial void OnSnapDealChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Amazon
        {
            get
            {
                return _Amazon;
            }
            set
            {
                OnAmazonChanging(value);
                ReportPropertyChanging("Amazon");
                _Amazon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amazon");
                OnAmazonChanged();
            }
        }
        private Nullable<global::System.Double> _Amazon;
        partial void OnAmazonChanging(Nullable<global::System.Double> value);
        partial void OnAmazonChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="cos_Model", Name="Tbl_ItemsDetails_More")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tbl_ItemsDetails_More : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tbl_ItemsDetails_More object.
        /// </summary>
        /// <param name="productID">Initial value of the ProductID property.</param>
        public static Tbl_ItemsDetails_More CreateTbl_ItemsDetails_More(global::System.Int64 productID)
        {
            Tbl_ItemsDetails_More tbl_ItemsDetails_More = new Tbl_ItemsDetails_More();
            tbl_ItemsDetails_More.ProductID = productID;
            return tbl_ItemsDetails_More;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int64 _ProductID;
        partial void OnProductIDChanging(global::System.Int64 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MerchantID
        {
            get
            {
                return _MerchantID;
            }
            set
            {
                OnMerchantIDChanging(value);
                ReportPropertyChanging("MerchantID");
                _MerchantID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MerchantID");
                OnMerchantIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MerchantID;
        partial void OnMerchantIDChanging(Nullable<global::System.Int32> value);
        partial void OnMerchantIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MerchantName
        {
            get
            {
                return _MerchantName;
            }
            set
            {
                OnMerchantNameChanging(value);
                ReportPropertyChanging("MerchantName");
                _MerchantName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MerchantName");
                OnMerchantNameChanged();
            }
        }
        private global::System.String _MerchantName;
        partial void OnMerchantNameChanging(global::System.String value);
        partial void OnMerchantNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ProductPrice
        {
            get
            {
                return _ProductPrice;
            }
            set
            {
                OnProductPriceChanging(value);
                ReportPropertyChanging("ProductPrice");
                _ProductPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductPrice");
                OnProductPriceChanged();
            }
        }
        private Nullable<global::System.Double> _ProductPrice;
        partial void OnProductPriceChanging(Nullable<global::System.Double> value);
        partial void OnProductPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductPriceCurrency
        {
            get
            {
                return _ProductPriceCurrency;
            }
            set
            {
                OnProductPriceCurrencyChanging(value);
                ReportPropertyChanging("ProductPriceCurrency");
                _ProductPriceCurrency = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductPriceCurrency");
                OnProductPriceCurrencyChanged();
            }
        }
        private global::System.String _ProductPriceCurrency;
        partial void OnProductPriceCurrencyChanging(global::System.String value);
        partial void OnProductPriceCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DiscountedPrice
        {
            get
            {
                return _DiscountedPrice;
            }
            set
            {
                OnDiscountedPriceChanging(value);
                ReportPropertyChanging("DiscountedPrice");
                _DiscountedPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiscountedPrice");
                OnDiscountedPriceChanged();
            }
        }
        private Nullable<global::System.Double> _DiscountedPrice;
        partial void OnDiscountedPriceChanging(Nullable<global::System.Double> value);
        partial void OnDiscountedPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Brand
        {
            get
            {
                return _Brand;
            }
            set
            {
                OnBrandChanging(value);
                ReportPropertyChanging("Brand");
                _Brand = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Brand");
                OnBrandChanged();
            }
        }
        private global::System.String _Brand;
        partial void OnBrandChanging(global::System.String value);
        partial void OnBrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Availability
        {
            get
            {
                return _Availability;
            }
            set
            {
                OnAvailabilityChanging(value);
                ReportPropertyChanging("Availability");
                _Availability = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Availability");
                OnAvailabilityChanged();
            }
        }
        private global::System.String _Availability;
        partial void OnAvailabilityChanging(global::System.String value);
        partial void OnAvailabilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NavigationURL
        {
            get
            {
                return _NavigationURL;
            }
            set
            {
                OnNavigationURLChanging(value);
                ReportPropertyChanging("NavigationURL");
                _NavigationURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NavigationURL");
                OnNavigationURLChanged();
            }
        }
        private global::System.String _NavigationURL;
        partial void OnNavigationURLChanging(global::System.String value);
        partial void OnNavigationURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MerchantProductID
        {
            get
            {
                return _MerchantProductID;
            }
            set
            {
                OnMerchantProductIDChanging(value);
                ReportPropertyChanging("MerchantProductID");
                _MerchantProductID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MerchantProductID");
                OnMerchantProductIDChanged();
            }
        }
        private global::System.String _MerchantProductID;
        partial void OnMerchantProductIDChanging(global::System.String value);
        partial void OnMerchantProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SKUID
        {
            get
            {
                return _SKUID;
            }
            set
            {
                OnSKUIDChanging(value);
                ReportPropertyChanging("SKUID");
                _SKUID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SKUID");
                OnSKUIDChanged();
            }
        }
        private global::System.String _SKUID;
        partial void OnSKUIDChanging(global::System.String value);
        partial void OnSKUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Custom1
        {
            get
            {
                return _Custom1;
            }
            set
            {
                OnCustom1Changing(value);
                ReportPropertyChanging("Custom1");
                _Custom1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Custom1");
                OnCustom1Changed();
            }
        }
        private global::System.String _Custom1;
        partial void OnCustom1Changing(global::System.String value);
        partial void OnCustom1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Custom2
        {
            get
            {
                return _Custom2;
            }
            set
            {
                OnCustom2Changing(value);
                ReportPropertyChanging("Custom2");
                _Custom2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Custom2");
                OnCustom2Changed();
            }
        }
        private global::System.String _Custom2;
        partial void OnCustom2Changing(global::System.String value);
        partial void OnCustom2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Custom3
        {
            get
            {
                return _Custom3;
            }
            set
            {
                OnCustom3Changing(value);
                ReportPropertyChanging("Custom3");
                _Custom3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Custom3");
                OnCustom3Changed();
            }
        }
        private global::System.String _Custom3;
        partial void OnCustom3Changing(global::System.String value);
        partial void OnCustom3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SerialNo
        {
            get
            {
                return _SerialNo;
            }
            set
            {
                OnSerialNoChanging(value);
                ReportPropertyChanging("SerialNo");
                _SerialNo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SerialNo");
                OnSerialNoChanged();
            }
        }
        private Nullable<global::System.Int32> _SerialNo;
        partial void OnSerialNoChanging(Nullable<global::System.Int32> value);
        partial void OnSerialNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreatedDate;
        partial void OnCreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion
    
    }

    #endregion
    
}
